In [1]:
import numpy as np

In [36]:
# video_array.reshape((num_frames, height, width, channels))

class VideoDimensionTransforms:
    def __init__(self, 
                 num_frames=None,height=240,width=320,channels=3,
                 num_frames_idx=0, 
                 height_idx=1, 
                 width_idx=2, 
                 channels_idx=3):
        self.dim_mapper = {
            num_frames_idx: num_frames,
            height_idx: height,
            width_idx: width,
            channels_idx: channels
        }
        self.num_frames=num_frames
        self.num_frames_idx=num_frames_idx
        self.height=height
        self.height_idx=height_idx
        self.width=width
        self.width_idx=width_idx
        self.channels=channels
        self.channels_idx=channels_idx

    def get_dim_mapper(self):
        return tuple([self.dim_mapper[i] for i in range(len(self.dim_mapper))])
    
    def get_final_dims(self):
        return (self.dim_mapper[self.num_frames_idx], 
            self.dim_mapper[self.height_idx], 
            self.dim_mapper[self.width_idx], 
            self.dim_mapper[self.channels_idx])

    def np1D_to_video(self, np_array):
        video = np_array.reshape(self.get_final_dims())
        return video

In [39]:
vdt = VideoDimensionTransforms(height_idx=     2,
                               num_frames_idx= 0,
                               width_idx=      1,
                               channels_idx=   3)
vdt.get_dim_mapper(), vdt.get_final_dims()

((None, 320, 240, 3), (None, 240, 320, 3))

In [10]:
f = 6
w = 5
h = 4
c = 3

x = np.arange(1,6*5*4*3+1)

In [11]:
x.shape, x[:10], "...", x[-10:]

((360,),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 '...',
 array([351, 352, 353, 354, 355, 356, 357, 358, 359, 360]))

In [26]:
xp = x.reshape((f,h,w,c))

In [27]:
xp.shape

(6, 4, 5, 3)

In [28]:
f1 = xp[0]
f1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]],

       [[31, 32, 33],
        [34, 35, 36],
        [37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54],
        [55, 56, 57],
        [58, 59, 60]]])